name: BellQuickTravelPoints
version: 1.0
main: pl.kerrex.bellquicktravel.BellQuickTravelPlugin
api-version: 1.13

commands:
  qt-register:
    description: Registers previously discovered bell as new quick travel point
    usage: /qt-register <new_point_name>
  qt:
    description: Teleports player to previously registered bell quick travel point
    usage: /qt <name_of_point>
  qt-list:
    description: Show list of available bell quick travel points
    usage: /qt-list